# Generated by Django 3.0.7 on 2020-10-08 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.CharField(max_length=15, verbose_name='дата публикации')),
                ('explanation', models.TextField(verbose_name='описание')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('image_url', models.ImageField(upload_to='', verbose_name='изображение')),
                ('image_hd_url', models.ImageField(upload_to='', verbose_name='изображение в hd')),
                ('media_type', models.CharField(max_length=20, verbose_name='тип медиа')),
                ('service_version', models.CharField(max_length=5, verbose_name='сервисаная версия')),
                ('received_date', models.DateTimeField(default=datetime.datetime(2020, 10, 8, 18, 20, 37, 70644, tzinfo=utc), verbose_name='дата получения данных')),
            ],
            options={
                'verbose_name': 'единица информации',
                'verbose_name_plural': 'единицы информации',
            },
        ),
    ]
