# Generated by Django 3.0.7 on 2020-10-10 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apod',
            name='image_hd_url',
            field=models.ImageField(upload_to='images_hd', verbose_name='изображение в hd'),
        ),
        migrations.AlterField(
            model_name='apod',
            name='image_url',
            field=models.ImageField(upload_to='images', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='apod',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 20, 56, 25, 518634, tzinfo=utc), verbose_name='дата получения данных'),
        ),
    ]
