# Generated by Django 3.0.7 on 2020-12-18 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201010_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apod',
            name='image_hd_url',
            field=models.CharField(max_length=100, null=True, verbose_name='изображение в hd'),
        ),
        migrations.AlterField(
            model_name='apod',
            name='image_url',
            field=models.CharField(max_length=100, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='apod',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 20, 54, 8, 529763, tzinfo=utc), verbose_name='дата получения данных'),
        ),
    ]
